---

##
## Install base configuration for all servers
##

- name: Install/Update Bartlby-UI
  hosts: all
  remote_user: root # It's important here
  vars:
    apache_vhosts:
      - {servername: "local.dev", documentroot: "/var/www/bartlby-ui"}
  roles:
    - bartlby-ui
