---

##
## Install base configuration for all servers
##

- name: Install/Update Bartlby-Dev Box
  hosts: all
  remote_user: root # It's important here
  vars:
    bartlby_mysql_user: root
    bartlby_mysql_password: docker
    bartlby_mysql_host: localhost
    bartlby_mysql_db: bartlby
    mysql_root_password: docker

  pre_tasks:
    - name: Update APT caches
      apt: update_cache=yes

    - name: install devbox required packages
      apt: state=installed pkg={{ item }}
      with_items:
        - git
        - openbsd-inetd
        - supervisor
        - openssh-server
        - wget
        - cron
        - vim
  tasks:
      - name: Enable SSH for root
        lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin yes" state=present
        notify:
          - restart ssh
  roles:
    - bartlby-agent
    - bartlby-php
    - bartlby-core
    - bartlby-plugins
    - bartlby-ui

  post_tasks:
    - name: Update Deploy Script
      get_url: url=https://raw.githubusercontent.com/Bartlby/bartlby-docker/master/deploy.sh dest=/opt/bartlby/deploy.sh mode=0777

    - name: get sample data file
      get_url: url=https://raw.githubusercontent.com/Bartlby/bartlby-docker/master/populate_sample_data.php dest=/root/1.php
      register: seed_change

    - name: seed sample data
      shell: cd /root; php 1.php
      ignore_errors: true
      notify: restart bartlby
      when: seed_change.changed


  handlers:
    - name: restart ssh
      action: service name=ssh state=restarted enabled=yes

    - name: restart bartlby
      shell: /opt/bartlby/etc/bartlby.startup restart
