---

##
## Install base configuration for all servers
##

- name: Install/Update Bartlby-Dev Box
  hosts: all
  remote_user: root # It's important here
  vars:
    bartlby_mysql_user: root
    bartlby_mysql_password: docker
    bartlby_mysql_host: localhost
    bartlby_mysql_db: bartlby
    mysql_root_password: docker
    mysql_databases:
      - name: bartlby
        encoding: latin1
        collation: latin1_general_ci

  pre_tasks:
    - name: Update APT caches
      apt: update_cache=yes

    - name: install devbox required packages
      apt: state=installed pkg={{ item }}
      with_items:
        - git
        - openbsd-inetd
        - supervisor
        - openssh-server
        - wget
        - cron
        - vim
  roles:
    - bartlby-agent
    - bartlby-php
    - bartlby-core
    - bartlby-plugins
    - bartlby-ui

  post_tasks:
    - name: Update Deploy Script
      get_url: url=https://raw.githubusercontent.com/Bartlby/bartlby-docker/master/deploy.sh dest=/opt/bartlby/deploy.sh mode=0777
