---

##
## Install base configuration for all servers
##

- name: Install/Update Bartlby-Core
  hosts: all
  remote_user: root # It's important here
  vars:
    bartlby_mysql_user: root
    bartlby_mysql_password: docker
    bartlby_mysql_host: localhost
    bartlby_mysql_db: bartlby

    mysql_root_password: docker


  roles:
    - bartlby-core
